#for local deployment only:

#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/justjava
#        registration:
#          keycloak:
#            provider: keycloak
#            client-name: alao
#            client-id: justjava
#            client-secret: 5qqrR6ymGiubGAB1KEGCSvSqDDbpb1cW
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email


#FOR RAILWAY DEPLOYMENT ONLY

server:
  # Uses the PORT provided by Railway, or defaults to 8081 if running locally
  port: ${PORT:8080}

spring:
  # --- DATABASE CONFIGURATION ---
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:34189/railway
    username: postgres
    password: ncb4sm1yhnq91t0s1o4e0m8z5j7smfhm
    driver-class-name: org.postgresql.Driver

  # --- HIBERNATE / JPA SETTINGS ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- SECURITY / KEYCLOAK CONFIGURATION ---
  security:
    oauth2:
      client:
        # 1. THE PROVIDER (Where Keycloak lives)
        provider:
          keycloak:
            issuer-uri: https://keycloak-production-f3ed.up.railway.app/realms/usersrealm

        # 2. THE REGISTRATION (Your App's Identity)
        registration:
          keycloak:
            provider: keycloak
            client-id: users
            client-secret: FcLFduxLqkUwY0C89mGkO3eTIfDg1toj
            authorization-grant-type: authorization_code
            scope: openid,profile,email

