
server:
  # Uses the PORT provided by Railway, or defaults to 8081 if running locally
  port: ${PORT:8080}

spring:
  # --- DATABASE CONFIGURATION ---
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:34189/railway
    username: postgres
    password: ncb4sm1yhnq91t0s1o4e0m8z5j7smfhm
    driver-class-name: org.postgresql.Driver

  # --- HIBERNATE / JPA SETTINGS ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- SECURITY / KEYCLOAK CONFIGURATION ---
  security:
    oauth2:
      client:
        # 1. THE PROVIDER (Where Keycloak lives)
        provider:
          keycloak:
            issuer-uri: https://keycloak-production-f3ed.up.railway.app/realms/usersrealm

        # 2. THE REGISTRATION (Your App's Identity)
        registration:
          keycloak:
            provider: keycloak
            client-id: users
            client-secret: FcLFduxLqkUwY0C89mGkO3eTIfDg1toj
            authorization-grant-type: authorization_code
            scope: openid,profile,email

#for deployment on railway
#spring:
#  application:
#    name: testhome
#
#  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
#
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    show-sql: false
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: ${KEYCLOAK_ISSUER_URI}
#        registration:
#          keycloak:
#            provider: keycloak
#            client-name: justjava
#            client-id: ${KEYCLOAK_CLIENT_ID}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email
#
#server:
#  port: ${PORT:8080}
#
#logging:
#  level:
#    org.springframework.security: INFO


